name: GitHub-Profile-3D-Contrib

on:
  # Atualiza todo dia às 6h UTC
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D profile
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@v1
        with:
          USERNAME: PedroSIUberaba
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A .
          git commit -m "Generated 3D profile contribution graph" || echo "No changes to commit"
          git push
