name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 6 * * *' # roda todo dia às 06h UTC
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          USERNAME: PedroSIUberaba

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Generated 3D contribution graph" || echo "No changes to commit"
          git push
